version: "3.9"

services:

  database_mariadb:
    container_name: bus-timetable-db
    image: mariadb:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=bus-timetable-system
      - MYSQL_USER=bus
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - bus-timetable-db-volume:/var/lib/mysql
    networks:
      - bus-timetable-network
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 30s
      timeout: 5s
      retries: 3

  springboot-bus-timetable-service:
    container_name: bus-timetable-service
    image: pacinho/bus-timetable-service:1.0.0-beta
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    ports:
      - 9090:8080
    depends_on:
      database_mariadb:
        condition: service_healthy
    environment:
      - spring.profiles.active=prod
      - spring.datasource.url=jdbc:mysql://database_mariadb:3306/bus-timetable-system
      - spring.datasource.username=bus
      - spring.datasource.password=1234
    volumes:
      - bus-timetable-app-volume:/app
    networks:
      - bus-timetable-network

volumes:
  bus-timetable-db-volume:
    driver: local
  bus-timetable-app-volume:
    driver: local

networks:
  bus-timetable-network:
    driver: bridge