version: "3.9"

services:

  database_mariadb:
    container_name: bus-timetable-db
    image: mariadb:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=bus-timetable-system
      - MYSQL_USER=bus
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - bus-timetable-volume:/var/lib/mysql
    networks:
      - bus-timetable-network

  springboot-bus-timetable-service:
    container_name: bus-timetable-service
    image: pacinho/bus-timetable-service:1.0.0-beta
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - 9090:8080
    depends_on:
      - database_mariadb
    environment:
      - spring.profiles.active=prod
      - spring.datasource.url=jdbc:mysql://database_mariadb:3306/bus-timetable-system
      - spring.datasource.username=bus
      - spring.datasource.password=1234
    networks:
      - bus-timetable-network

volumes:
  bus-timetable-volume:

networks:
  bus-timetable-network:
    driver: bridge