spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: 'local'
  main:
    banner-mode: off
server:
  servlet:
    context-path: '/api/bus-timetable-system'
