spring:
  jpa:
    hibernate:
      ddl-auto: validate

#  h2:
#    console:
#      enabled: true
#      path: '/console'

  datasource:
    url: 'jdbc:mysql://localhost:3308/bus-timetable-system'
    username: 'bus'
    password: '1234'

  flyway:
    baselineOnMigrate: true