insert into bus_stop(name, address) values ('Os. Bukowe 01','Koszalin os. Bukowe 12');
insert into bus_stop(name, address) values ('Lelewela 01','Koszalin ul. Lelewela 5');
insert into bus_stop(name, address) values ('Śniadeckich 01  ','Koszalin ul. Śniadeckich 1');
insert into bus_stop(name, address) values ('Śniadeckich Politechnika 01','Koszalin ul. Śniadeckich 24');
insert into bus_stop(name, address) values ('Staszica 02','Koszalin ul. Staszica 14');
insert into bus_stop(name, address) values ('Kwiatkowskiego 02','Koszalin ul. Kwiatkowskiego 18');
insert into bus_stop(name, address) values ('Wąwozowa 02','Koszalin ul. Wąwozowa 8');
insert into bus_stop(name, address) values ('Jamno 02','Jamno ul. Koszalińska 1');
insert into bus_stop(name, address) values ('Łabusz 02','Łabusz ul. Zachodnia 33');

insert into bus_stop(name, address) values ('Zagroda Jamneńska 02','Jamno, ul. Zagroda Jamneńska 11');
insert into bus_stop(name, address) values ('Jamno 01','Jamno, ul. Koszalińska 17');
insert into bus_stop(name, address) values ('Wąwozowa','Koszalin, ul. Wąwozowa 12');
insert into bus_stop(name, address) values ('Kwiatkowskiego 01','Koszalin, ul. Kwiatkowskiego 4');
insert into bus_stop(name, address) values ('Jana Pawła II 01','Koszalin, ul. Jana Pawła II 8');
insert into bus_stop(name, address) values ('Staszica 01','Koszalin, ul. Staszica 15');
insert into bus_stop(name, address) values ('Śniadeckich Politechnika 02','Koszalin, ul. Śniadeckich 10');
insert into bus_stop(name, address) values ('Śniadeckich Hala 02','Koszalin, ul. Śniadeckich 15');
insert into bus_stop(name, address) values ('Śniadeckich 02','Koszalin, ul. Śniadeckich 20');
insert into bus_stop(name, address) values ('Lelewela 02','Koszalin, ul. Lelewela 2');
insert into bus_stop(name, address) values ('Os. Bukowe 02','Koszalin, os. Bukowe 1');